name: Build fpnavigator Windows

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - upgrade

jobs:
  build-fpnavigator-windows:
    name: Build fpnavigator ${{ matrix.config.name }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        config:
        - name: Windows-Win64
          win: win64
          arch: x86_64

        - name: Windows-Win32
          win: win32
          arch: i686

    steps:
      - name: List available VC Redist folders (for debugging)
        run: tree /f "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\redist"

      - name: Install MozillaBuild
        run: |
          Invoke-WebRequest -Uri https://ftp.mozilla.org/pub/mozilla/libraries/win32/MozillaBuildSetup-3.4.exe -OutFile MozillaBuildSetup-3.4.exe
          .\MozillaBuildSetup-3.4.exe /S /v/qn | Write-Output
          del .\MozillaBuildSetup-3.4.exe
        shell: pwsh

      - uses: ChristopheLav/windows-sdk-install@v1
        with:
          version-sdk: ${{ matrix.config.arch == 'x86_64' && '26100' || '22621' }}
          features: 'OptionId.DesktopCPPx64,OptionId.DesktopCPPx86'

      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Copy mozconfig
        run: Copy-Item .github\workflows\build-fpnavigator-windows\mozconfig-${{ matrix.config.win }} -Destination .\.mozconfig
        shell: pwsh

      - name: debug dirs
        run: |
          C:\mozilla-build\start-shell.bat echo '/c'
          C:\mozilla-build\start-shell.bat ls /c
          C:\mozilla-build\start-shell.bat echo '/c/a'
          C:\mozilla-build\start-shell.bat ls /c/a
          C:\mozilla-build\start-shell.bat echo '/d'
          C:\mozilla-build\start-shell.bat ls /d
          C:\mozilla-build\start-shell.bat echo '/d/a'
          C:\mozilla-build\start-shell.bat ls /d/a

      - name: mach configure
        run: |
          C:\mozilla-build\start-shell.bat /d/a/${{ github.event.repository.name }}/${{ github.event.repository.name }}/.github/workflows/build-fpnavigator-windows/mach-passthrough-windows.sh /d/a/${{ github.event.repository.name }}/${{ github.event.repository.name }} configure
        shell: pwsh

      - name: mach build
        run: |
          C:\mozilla-build\start-shell.bat /d/a/${{ github.event.repository.name }}/${{ github.event.repository.name }}/.github/workflows/build-fpnavigator-windows/mach-passthrough-windows.sh /d/a/${{ github.event.repository.name }}/${{ github.event.repository.name }} build
        shell: pwsh

      - name: mach package
        run: |
          C:\mozilla-build\start-shell.bat /d/a/${{ github.event.repository.name }}/${{ github.event.repository.name }}/.github/workflows/build-fpnavigator-windows/mach-passthrough-windows.sh /d/a/${{ github.event.repository.name }}/${{ github.event.repository.name }} package
        shell: pwsh

      - uses: actions/upload-artifact@v4
        with:
          name: flashpointnavigator-windows-${{ matrix.config.win }}
          path: obj-${{ matrix.config.arch }}-pc-mingw32/dist/flashpointnavigator-*
